# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection

spring:
  datasource:
    jndi-name: java:/comp/env/jdbc/konta

  # ===============================
  # = JPA / HIBERNATE
  # ===============================

  # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
  # stripped before adding them to the entity manager).

  # Show or not log for each sql query
  jpa:
    show-sql: true
    format_sql: true
    use_sql_comments: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "update" the database
      # schema will be automatically updated accordingly to java entities found in
      # the project
      ddl-auto: create
      # Naming strategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      # Allows Hibernate to generate SQL optimized for a particular DBMS
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDataSource

#  jmx:
#    enabled: false
#
#com:
#  accenture:
#    archetype:
#      configuration:
#        # Spring Security basic authentication configuration
#        security:
#          user: admin
#          password: admin
#endpoints:
#  hypermedia:
#    enabled: true
#
#
#
logging:
  level:
    org:
      springgramework: TRACE
    com:
      tuxdev:
        kontaweb: DEBUG
#  file: logs/konta.log

# ===============================
# = OAUTH2
# ===============================
# Set here configurations to enable OAUTH2 security to the exposed APIs
#security:
#    oauth2:
#      client:
#        clientId: 233668646673605
#        clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#        accessTokenUri: https://graph.facebook.com/oauth/access_token
#        userAuthorizationUri: https://www.facebook.com/dialog/oauth
#        tokenName: oauth_token
#        authenticationScheme: query
#        clientAuthenticationScheme: form
#      resource:
#        userInfoUri: https://graph.facebook.com/me